server:
  port: 8020

spring:
  application:
    name: system-service

  datasource:
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 7540000E

    druid:
      initial-size: 5
      min-idle: 10
      max-active: 30
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/